server.ip=127.0.0.1
server.tcp.port=6000
server.udp.port=6001
round.duration.seconds=180
tick.rate.ms=50
max.players=8
grace.timer.ms=5000
freeze.duration.ms=3000
zone.capture.time.ms=2000
item.spawn.interval.ms=8000
points.per.zone.tick=2
item.energy.value=100
item.weapon.value=0
tag.penalty.points=300
speed.boost.duration.ms=5000
speed.boost.multiplier=2